"""
dashboard/pages/4_Monitoring.py
---------------------------------
Live monitoring dashboard.

Displays:
  - Backend service metrics from GET /metrics
  - Prediction distribution donut
  - RAG retrieval stats bar
  - KPI cards: request count, error rate, avg latency, uptime
  - Refusal rate, hit-rate
  - Drift alerts (loads monitoring/drift_summary.json if present)
  - Token usage stats
  - Manual refresh button
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import streamlit as st

from dashboard.utils.api_client import get_metrics, health_check
from dashboard.utils.config import CONFIG
from dashboard.components.cards import kpi_card, alert, status_banner
from dashboard.components.charts import (
    prediction_donut, rag_metrics_bar, kpi_line
)
from dashboard.components.tables import metrics_summary_table

st.set_page_config(page_title="Monitoring · Meridian", page_icon="📊", layout="wide")

_CSS = Path(__file__).parents[1] / "assets" / "styles.css"
if _CSS.exists():
    st.markdown(f"<style>{_CSS.read_text()}</style>", unsafe_allow_html=True)

# ── Header ────────────────────────────────────────────────────────────────────
st.markdown("# 📊 Monitoring Dashboard")
st.markdown("Live service metrics, prediction distributions, and drift detection results.")

with st.sidebar:
    st.markdown("## 📊 Monitoring")
    st.caption(f"Backend: `{CONFIG.api_base_url}`")
    st.divider()
    if st.button("🔄 Refresh Metrics", use_container_width=True):
        st.cache_data.clear()
    auto_refresh = st.checkbox("Auto-refresh (30s)", value=False)
    if auto_refresh:
        import time
        st.rerun()

# ── Backend health ─────────────────────────────────────────────────────────────
health = health_check()
healthy = not health.get("_error") and health.get("status") == "ok"
status_banner(healthy, model_version=health.get("model_version", ""), environment=CONFIG.environment)

st.divider()

# ── Live metrics ──────────────────────────────────────────────────────────────
st.markdown("### 🔴 Live Service Metrics")

with st.spinner("Loading metrics…"):
    metrics = get_metrics()

if metrics.get("_error"):
    alert(f"Could not load metrics: {metrics['_message']}", kind="warning")
    st.info("The backend may be offline. Showing local monitoring artifacts below.")
    metrics = {}

if metrics and not metrics.get("_error"):
    pred_dist = metrics.get("prediction_distribution", {})
    rag_stats = metrics.get("rag_retrieval_stats", {})

    # ── KPI strip ─────────────────────────────────────────────────────────────
    k1, k2, k3, k4 = st.columns(4)
    with k1:
        kpi_card("Total Requests", str(metrics.get("total_requests", 0)), color="#6366f1")
    with k2:
        kpi_card("Error Count", str(metrics.get("error_count", 0)),
                 color="#ef4444" if metrics.get("error_count", 0) > 0 else "#22c55e")
    with k3:
        kpi_card("Avg Latency", f"{metrics.get('avg_latency_ms', 0):.1f} ms", color="#f59e0b")
    with k4:
        kpi_card("Uptime", f"{metrics.get('uptime_seconds', 0):.0f} s", color="#22c55e")

    st.markdown("")

    k5, k6, k7, k8 = st.columns(4)
    with k5:
        kpi_card("Total Predictions", str(pred_dist.get("total_predictions", 0)), color="#818cf8")
    with k6:
        kpi_card("Positive Rate", f"{pred_dist.get('positive_rate', 0):.1%}", color="#22c55e")
    with k7:
        kpi_card("RAG Queries", str(rag_stats.get("total_queries", 0)), color="#a78bfa")
    with k8:
        kpi_card("RAG Refusal Rate", f"{rag_stats.get('refusal_rate', 0):.1%}",
                 color="#ef4444" if rag_stats.get("refusal_rate", 0) > 0.3 else "#f59e0b")

    st.markdown("")

    # ── Charts ────────────────────────────────────────────────────────────────
    chart_col1, chart_col2 = st.columns([1, 1])

    with chart_col1:
        pos = pred_dist.get("positive_predictions", 0)
        neg = pred_dist.get("negative_predictions", 0)
        st.plotly_chart(prediction_donut(pos, neg), use_container_width=True)

    with chart_col2:
        if rag_stats:
            st.plotly_chart(rag_metrics_bar(rag_stats), use_container_width=True)

    # ── Metrics table ─────────────────────────────────────────────────────────
    with st.expander("📋 Full Metrics Summary Table"):
        metrics_summary_table(metrics)

    with st.expander("📋 Raw JSON Response"):
        st.json(metrics)

st.divider()

# ── Local monitoring artifacts ─────────────────────────────────────────────────
st.markdown("### 📁 Local Monitoring Artifacts")
st.caption("Loaded from `monitoring/` directory — generated by `src/monitoring/ml_drift.py` and `rag_monitor.py`.")

_MONITORING_DIR = Path(__file__).resolve().parents[3] / "monitoring"

# Drift summary
drift_path = _MONITORING_DIR / "drift_summary.json"
if drift_path.exists():
    with st.expander("⚠️ Drift Summary (`monitoring/drift_summary.json`)", expanded=True):
        try:
            drift = json.loads(drift_path.read_text())
            drifted = drift.get("dataset_drift_detected", False)

            if drifted:
                st.error(f"🚨 Dataset drift detected! **{drift.get('n_drifted_columns', 0)}** columns drifted.")
            else:
                st.success("✅ No dataset drift detected.")

            d1, d2, d3 = st.columns(3)
            with d1:
                kpi_card("Drift Detected", "Yes" if drifted else "No",
                         color="#ef4444" if drifted else "#22c55e")
            with d2:
                kpi_card("Drifted Columns", str(drift.get("n_drifted_columns", 0)),
                         color="#ef4444")
            with d3:
                kpi_card("Stable Columns", str(drift.get("n_not_drifted_columns", 0)),
                         color="#22c55e")

            if drift.get("drifted_columns"):
                st.markdown("**Drifted columns:** " + ", ".join(
                    [f"`{c}`" for c in drift["drifted_columns"]]))

            col_details = drift.get("column_details", [])
            if col_details:
                import pandas as pd
                df = pd.DataFrame(col_details)
                st.dataframe(df, use_container_width=True, hide_index=True)

            st.caption(f"Generated at: {drift.get('generated_at', 'N/A')}")
        except Exception as exc:
            alert(f"Could not parse drift_summary.json: {exc}", kind="warning")
else:
    st.info("No `monitoring/drift_summary.json` found. Run `python src/monitoring/ml_drift.py` to generate it.")

# Metrics JSON
metrics_path = _MONITORING_DIR / "metrics.json"
if metrics_path.exists():
    with st.expander("📊 Monitoring Metrics (`monitoring/metrics.json`)"):
        try:
            m = json.loads(metrics_path.read_text())
            summary = m.get("summary", {})

            if "rag_query_summary" in summary:
                rqs = summary["rag_query_summary"]
                r1, r2, r3, r4 = st.columns(4)
                with r1:
                    kpi_card("RAG Queries (log)", str(rqs.get("count", 0)), color="#6366f1")
                with r2:
                    kpi_card("Hit Rate", f"{rqs.get('hit_rate', 0):.1%}", color="#22c55e")
                with r3:
                    kpi_card("Avg Similarity", f"{rqs.get('avg_top_k_similarity', 0):.3f}", color="#f59e0b")
                with r4:
                    kpi_card("Avg Token Usage", str(rqs.get("avg_token_usage", 0)), color="#a78bfa")

            st.caption(f"Generated at: {m.get('generated_at', 'N/A')} · {m.get('summary', {}).get('total_events', 0)} events")
        except Exception as exc:
            alert(f"Could not parse metrics.json: {exc}", kind="warning")

# HTML drift report link
report_path = _MONITORING_DIR / "report.html"
if report_path.exists():
    with st.expander("🌐 Evidently HTML Report (`monitoring/report.html`)"):
        st.success(f"✅ Drift report available at: `{report_path}`")
        st.info("Open this file in a browser to view the full Evidently interactive drift report.")
        st.caption(f"File size: {report_path.stat().st_size / 1024:.0f} KB")
